#+TITLE: Approach to and style of ski traverses
#+AUTHOR: Brian J. Oney
#+DATE: 2023-01-01
#+CATEGORY: tips
#+PROPERTY: TAGS techniques, philosophy, alpine-style
#+OPTIONS: toc:nil
#+ORDER: 3
#+LANGUAGE: en


* Expedition style
Let me establish two approaches to a ski traverses longer than a week, as I
understand them. The classical approach is similar to a polar expedition. This
expedition style entails harnessing a heavy (>1kg) sled that cannot be
practically carried, taking a lot of liquid fuel, a smaller pack, and
making an average progress each day of 8-40km, summing up and down. Ski tours
are loops starting at basecamp when the time is right.  Passable terrain is
limited by the skill to handle the heavy sled, but is practically limited to
mellow terrain with few obstacles. The range of total distances covered can be
very high (1000km), strongly depending on conditions. Weight is always an
issue but there's a sled. This approach is great for long-lived basecamps in
remote places.

* Alpine style
I will focus here on the application of alpinism's 'light and fast' style to
ski traverses. I'll call them alpine style ski traverses.  The key
difference between expedition style and alpine style is speed. Alpine style
assumes speedy sustained progress, typically twice as fast as expedition
style. The choices of gear are important, as weight heavily influences
speed. Training requires a solid aerobic base, upon which a lot of training
with a heavy pack can be done in the off season.


Alpine style ski traverses entail carrying everthing in a large, yet light and
compressible backpack, possibly with a small (<1kg) packable sled (e.g. a
boggy, see http://www.johnbaldwin.ca/trip-planning-toboggan.asp) when
starting.  Average progress each day can vary wildly from 10km to 50km per
day, summing up and down. Passable terrain is limited by each group member's
ability to ski with a loaded pack. The range of distances to be covered are
moderate to high (100 to 500km) between resupplies, are limited by the speed
of the group and their ability to carry the sustaining food and fuel, and, of
course, are strongly dependent on conditions. Weight is a core issue.

The alpine style allows access to the much steeper terrain. Thinking of
forward progress in distance is not useful. I'll define an 'alpine unit' based
on the military approximation, but is taught in certain German circles as a
Leistungskilometer (effort kilometer). I was taught the same concept but the
word Einheit (unit) was used.

The concept of an alpine unit hinges on the assumption that one kilometer of
distance requires the same amount of effort and time as a hundred meters of
altitude gain.  *The alpine unit equates 100m vertical gain with 1000m
distance.* A handy calculation for imperial units is difficult on the fly, so
roughly convert vertical feet to meters. Also, overlaying the UTM grid (1km by
1km) on a map allows for relatively precise determination of distance, without
the aid of digital technology. A good first approximation for the time
necessary for an alpine unit is 15 minutes or 4 units per hour. Although
individuals may be much much faster, the time taken for a unit must be
constantly observed and used for planning forward progress both in the short
and long terms. Note, an old and wise mountain guide says that this equation
needs modification when the terrain is very flat (<5°) or very steep
(>35°). When it is flat, only consider the distance, when it is steep, only
consider the height.

The number of alpine units sustained per day over the course of a week is an
important result of reflection when planning the next ski traverse. A first
approximation of this sustained progress could be half of the normal alpine
units done on a day's ski tour. If you are strong with a heavy pack, take 3/4
of the speed on a day's ski tour. 

Alpine style ski traverses allow for continuous replanning of the route, fast
exits, avoidance or mitigation of bad weather, and, my favorite, complete
immersion in a mountain range. This is the approach of the pioneers of ski
traverses, light and therefore fast and nimble. Bill Briggs did not have a
sled on the Bugaboo to Rogers Traverse. With the constantly improving
lightweight gear, improving map material, denser weather observation networks,
improved remote sensing data availability and access, this practice can become
safer and more enjoyable with time, especially when experience allows you to
whittle down your kit, and you condition yourself further.

* My alpine style ski traverses

In my case, my pack can weigh a maximum of about 25kg, including skis, and I
am still having fun. I aim for 40 units per day, which assumes some poor
conditions and some good conditions for progress. My daily progress on my last
traverse in Bulgaria averaged at about alpine 45 units per day sustained over
8 days, including a rest day. That's not fast, but it suffices to cover
considerable ground (360 alpine units total). I used 106mm wide skis
and freeride bindings. I could have been faster with narrower skis, lighter
bindings, or scale-based skis. I have much room to learn and improve.

I am thankful for the concise book on winter mountaineering 'Bergsport Winter'
in German. I am most thankful for all my mentor's and friend's guidance and
patience. They were pivotal in aiding me to develop the necessary skills of
determining avalanche risk, orienteering in all conditions, detailed map study
and route planning, as well as little bits of information to make prolonged
stays in the often harsh winter landscape enjoyable. They continue to be very
helpful and good company. Thank you!
