#+TITLE: Planning a ski traverse of the US Continental Divide
#+AUTHOR: Brian J. Oney
#+CATEGORY: winter-cdt
#+PROPERTY: TAGS planning, CDT
#+OPTIONS: toc:nil
#+LANGUAGE: en

* Timing

Of all things, the timing and sequence of a ski traverse of the US Continental Divide is where flexibility will be necessary.

Currently, I see two options, and list them in order of my preference. I would
start northbound mid-November, most likely exiting at Cumbres Pass, Colorado,
but possibly continuing northward until the avalanche conditions become too
unpredictable. Another less preferable option, but possibly the only reasonable
option for a continuous footpath border to border, would be to start southbound
sometime in January or February, with the goal of being in Grand Lake, Colorado
by early April.


Why the two options? The technical crux of wintertime CDT is the combination
of steep terrain of central and southern Colorado and notoriously weak
snowpack. This area is reserved for the late springtime.  Past Grand Lake and
the Front Range, the CDT begins to mellow, and the snowpack thickens.

Why is starting southbound mid-Winter my second preference? In general, it is
better to walk up warm, crusty, and usually more stable southern faces in the
sun, and ski quickly through colder, softer northerly aspects, where weak layers
lurk and safety distances are easily maintained. Thus, the disadvantages would
be missing a considerable amount of powder, hiking in the coldest temps on the
mountain (only bad when it's frigid), hiking on the most dangerous aspects of
the mountain (increasing the time of exposure to risk), possibly hiking up with
crampons and skis on my back and having to walk down the barren southern slope,
and, finally, being in New Mexico in June, a hot and windy place at that time of
year. None of those are dealbreakers.

* Path and Terrain

The terrain along the CDT is typically mellow, and avoids the common ski
objectives that are often a short distance away. For example, the CDT path
through the Wind River range could not be more gentle given the surrounding
terrain. Plan on deviating from the snow-covered CDT to avoid avalanche risks
and to chase good snow. This way the fun remains.

Above all, being loyal to a snow-covered footpath brings danger and unnecessary toil.
The following principles keep it fun and safer.

* Principles

1. Safety first.
   - If we need to wait out a storm cycle, we ride
     powder or rest until the snow settles. I carry a helmet, ice axe, beacon, probe,
     proper shovel, ski goggles, satellite transceiver, etc. Safety first.
2. Proper planning is safety.
   - Food, fuel, weather, and above all time planning are our tools to be safe.
3. Speed is safety.
   - Weather changes, gear fails, people fall ill. Uphill speed is our
     friend. Slowness begets slowness. We need to be fast. 2000 vertical feet
     (600 meters) gain per hour with a load (10-13kg) and a good track should
     be possible when needed. We should be able to sustain 20 to 30 Alpine units (1km distance or 100m vertical) uphill per day.
   - Gear must be optimized for our speed. Speed during travel, cooking, camping is key.
4. Redundant systems are necessary.
   - Redundancy in navigation (altimeter and paper maps, compass and map, cell
     phone, GPS), shelter (tent, poncho tarp, proper shovel for snow cave) and
     sleeping systems (repair materials) is necessary.
5. Social coherence trumps fun.
   - We stick together within reason.
6. Rest and recovery is very important.
   - We need to ensure we can handle a 14-day traverse in deep snow. Thorough
     nightly rest is important to recover.

* Systems

- Light backcountry skis with kicker skins (e.g. skimo race skins) or scaled bases and climbing skins. Scaled bases are helpful for efficiency, but ice up. A normal pair of skis with kicker skins is a better option in my opinion.
  - I am open to backcountry cross country skis for certain sections. But I
    trust lightweight touring skis and can comfortably skate with them.
- Tent: Assuming shelter can be found in the forest, my *current* choice: Seek Outside hot-tent and medium u-turn wood stove or Durston X-mid 2, fly only.
  - Note: I have tried digging a snow cave every night. It is too much work and too slow, but is a good backup shelter.
- If using a gas stove, a zipperless down sleeping bag (-20°F) and a synthetic overquilt. Timmermade gear serves me very well.
- If using a gas stove, a zipperless down sleeping bag (-20°F) and a synthetic overquilt. Timmermade gear serves me very well.
- If using a packable woodstove, zipperless down sleeping bag (-20°F) without overquilt.
  - Note: I have tried extending all the 3-season ultralight systems for winter and failed. This is my current trusted system.
- Melt snow, heat water: gas stove for speed first, wood stove second. An
  (additional) option is using a foldable Nalgene cantene between the back and
  backpack (and combine no-cook with cold-soak). It is essential to plan in
  water collection at flowing water.
  - Note: I have tried the Trail Designs fissure alcohol systems for winter
    traverses. They work well and are reliable, but are fidgety, slow, and stink too much to use in a tent.

Why no sled? Please read about my [[./approach-and-style.org][approach to ski traverses]].

* Finances

Without the gear investments (about 8k$ upfront!), I would budget
at least 10k$. Weather-driven stays in town are a variable that may inflate that
number. I still need to research what permits will be necessary for certain sections.

* People

Myself: Experienced alpine winter backcountry tour guide, splitboard and
ski mountaineer, powderhound, climate activist.  I am a climate scientist
turned firmware engineer, a little over 6' (184cm), 75kg, and injury-resistant
and well-conditioned. I was born in New Mexico, and live in Switzerland with
my wife.

I have been out in the snow since I was little, but since 2012 every season
>80 days touring, with an upward trend.  For weight and efficiency reasons, I
learned how to ski recently, after 9 years of snowboarding and 9 years of
almost solely splitboarding. Skis just make more sense for traverses;
therefore, I ski, and I skied well enough for my traverse in Bulgaria, with
plenty of terrible snow, and I can ski well enough for this traverse of the
Continental Divide.

I have never walked any of the long trails in summer. I plan to when I am older.
I have done multiple ski traverses in Switzerland and Bulgaria. I truly enjoy
being out in the wild, especially in winter. My favorite thing to do is a ski
traverse. I enjoy 'bad' weather, also in winter. I view an attempt to walk the
CDT in winter, as a string of ski traverses.

Lukas S.: Experienced ski mountaineer, firmware engineer, long-time tour
partner of Brian, living in Switzerland.

* Considering a wager?

If you are interested, please read about my [[./approach-and-style.org][approach to ski traverses]], read
through [[./skills-and-training.org][skills and abilities for an attempt]], and take time to reflect and
decide.

