#+TITLE: Plan for winter Continental Divide Trail
#+AUTHOR: Brian J. Oney
#+TAGS: wintercdt
#+LANGUAGE: en

* Timing


With the goal to maintain a continuous northbound footpath, I intend to start
sometime between October 15th and November 1st. The finishing goal for this
initial push is the arrive in Grand Lake, Colorado before a break for
Christmas. Specifically, I plan to stop on December 23rd to go spend Christmas
with family.

Why Grand Lake specifically? The main priority is to avoid walking through
steep terrain on a weak snowpack. I will not walk through sketchy avalanche
conditions (level above 2) and steep terrain (slope angle above
30⁰). Persistent weak layers are very common for a Colorado snowpack, and
these weak layers are to be taken dead seriously. The idea to start early
bases on the lower probability of buried weak layers early on in the season,
due to the thinner snowpack and hence fewer layers. It is quite possible that
we will be skiing through a snowpack composed completely of faceted snow. We
just have to watch out for rocks and sticks. Past Grand Lake, after Ptarmigan
Point, the CDT begins to mellow, and weak layers ought to be less of an
issue. The technical crux of the trip will then be behind us, and our focus
shifts to weathering the winter and making progress for a while.

Why not southbound starting in February? In general, it is better to walk up
warm, crusty, and usually more stable southern faces in the sun, and ski
quickly through colder, softer northerly aspects, where weak layers lurk and
safety distances are easily maintained. Also, after approximately 2.5 months,
mid-April, I'd be in central Colorado, approximately, and there would be no
guarantee that the snowpack is stable.

Probably most importantly, I don't have a partner yet. The three weeks until
we may hit considerable snow in New Mexico and switch to skis will serve as an
extended trail date for anyone who chooses to join me. We will work out our
routines and quirks by Christmas, I hope. Also, on the New Mexican portion, we
can get our legs and backs ready for the fun skiing part up north.

Alternatively, if the snowpacks in Colorado look terrible already in late
November and early December, we will consider skipping over Colorado to
Wyoming and coming back in late Spring. If we start on October 15th, it is
likely that we'll make it to north-central Colorado by Christmas. Being past
the San Juans and Collegiate Peaks by then would be a relief to me, knowing
that the notoriously bad snowpacks would be behind us. If it's a low snow year,
we still may not have been able to ski. I hope for plenty of snow and a stable
snowpack in Colorado.

* Path and Terrain
The terrain along the CDT is typically mellow, avoiding the common ski
objectives which are often a short distance away. I plan on deviating from the
classical CDT path to avoid avalanche risks and to chase good snow. This will
depend also on my partners. 

For example, the CDT path through the Wind River range could not be more
gentle given the surrounding terrain. I guess that by the time we get there,
we may be itching for more ambitious path. We'll see then and there what makes
sense.

Above all, I am not loyal to a snow-covered footpath. We must optimize
according to the following principles.

* Principles
1. Safety first.
   - If we need to wait out a vicious storm cycle in a ski town, we ride
     powder until the snow settles. I carry a helmet, ice axe, beacon, probe,
     proper shovel, ski goggles, satellite transceiver, etc. Safety first.
2. Proper planning.
   - Food, fuel, weather, and above all time planning are our tools.
3. Speed is safety.
   - Weather changes, gear fails, people fall ill. Speed is our
     friend. Slowness begets slowness. We need to be fast. 2000 vertical feet
     (600 meters) gain per hour with a load (10-13kg) and a good track should
     be possible when needed.
   - Gear is optimized for our speed. Speed during travel, cooking, camping is key.
4. Redundant systems.
   - Redundancy in navigation (altimeter and paper maps, compass and map,
     GPS), shelter (tent, poncho tarp, shovel for snowcave) and sleeping
     systems (repair materials) is important.
5. Social coherence trumps fun.
   - We stick together within reason.
6. Rest is very important.
   - We need to ensure we can handle a 10-day traverse in deep snow. Thorough
     nightly rest is important.

* Systems
- Light backcountry skis with scaled bases and climbings skins. Scaled bases are necessary for efficient.
  - I am open to backcountry cross country skis for certain sections. But I
    trust lightweight touring skis and can comfortably skate with them. 
- Tent: My choice: Durston X-mid 2 fly (or Pro gutted), Candidates: Durston
  X-mid 2 with solid inner tent, HMG UltaMid 2, Tarptent Stratospire Li with
  solid inner.
  - Also, I have tried digging a snow cave every night. It is too much work. Good backup shelter.
- Zipperless down sleeping bag (-20°F) with DCF vapor barrier clothing. Timmermade gear serves me very well.
  - Note: I have tried extending all the 3-season ultralight systems for winter and
    failed. This is my current trusted system.
- Melt snow, heat water: MSR reactor. An (additional) option is using a
  foldable Nalgene cantene between the back and backpack (and combine no-cook
  with cold-soak). It is essential to plan in water collection at flowing
  waters. Otherwise, we carry too much fuel.
  - Note: I have tried the Trail Designs fissure alcohol systems for winter
    traverses. They work well, but are fidgety, slow, and stink too much to use in a
    tent. I think the MSR reactor works better for the weight and is more
    versatile (cook/hang in tent, fuel-to-snow-melted ratio). 50g of fuel per person per day.

* Finances
Without the gear investments (about 8k$ upfront!), I would budget
10k$. Weather-driven stays in town are a variable that may inflate that
number. I still need to research what permits will be necessary for certain sections.

* People
Myself: Experienced alpine winter backcountry *tour* guide, splitboarder,
skier, powder hound, climate activist.  I am 37 years old, a climate scientist
turned firmware engineer, a little over 6' (184cm), 75kg, and injury-resistant
and well-conditioned. I was born in New Mexico, and live in Switzerland with
my wife, with no kids.

I have been out in the snow since 2015 every winter for ski touring >50 days
each season.  For weight and efficiency reasons, I learned how to ski
recently, after 9 years of snowboarding and 9 years of splitboarding. Skis
just make more sense for traverses; therefore, I ski.

I have never walked any of the long trails. I plan to when I am older. I have
done multiple ski traverses in Switzerland and Bulgaria.  I truly enjoy being
out in the wild, especially in winter.  My favorite thing to do is a ski
traverse. I view an attempt to walk the CDT in winter as a string of ski
traverses.


You: Experienced winter backcountry *ski* tourer. You should be passionate
about winter, cold-resistant, have a positive outlook and be full of energy.
Also, I am open to partial companionship. If you have the skills, please join
me for a certain part!

* Fundraiser
I sure would like to take the opportunity set a fundraiser challenge and have
people join me in donating money to a cause. My best idea is to find an
organization the supports less fortunate communities to build out their
renewable energy mix, with the goal of long-term energy autonomy. I am open to
ideas. I guess I'd donate a dollar per mile progress.

* Interested in joining me?
I will only do the CDT in winter if I have a partner. If you are interested,
please read through [[../responses-to-obvious-questions][responses to obvious questions]], and take time to reflect
and decide.  Let's talk. We should take one of the [[https://UphillAthlete.com][Uphill Athlete]] courses
(probably the [[https://uphillathlete.com/grand-traverse-ski-training-plan/][12 Week Grand Traverse Training Plan]]) together at the very
least.

