#+TITLE: Disclaimer / Data Protection
#+AUTHOR: Brian J. Oney
#+LANGUAGE: en

* Disclaimer
The contents of this website were carefully created by Brian J. Oney.

Address: Brian Oney | Bahnhofstrasse 91 | 8803 Rüschlikon | Switzerland

Email: brian PERIOD j STOP oney ÄT gmail PUNKT com

* Definitions
  - The author ist Brian J. Oney.
  - Knowledge, hints, suggestions are used for the further education of the readers with the intention of using them in winter sports.
  - The organization is called Snowy Experiments.
  - The male gender in the following text applies to all genders.
  - A user is a person who retrieves information from this website.
  
* Liability for Product
Information is provided on this website for educational purposes. This
information is based on scientific reports and on the experience of
author. This information is used under the own responsibility and risk. In the
event of accidents and injuries, the user. Insurance is the responsibility of
the participant.

* Liability for content

The contents of our pages were created with great care. For the
However, we can guarantee that the content is correct, complete and up-to-date
assume no liability. Obligations to remove or block the
This does not apply to the use of information in accordance with general laws
untouched. However, liability in this regard is only applicable from the point in time at which
Knowledge of a specific infringement possible. Upon notification of
corresponding violations of the law, we will remove this content immediately.

* Liability for links

Our content contains links to external websites of third parties, and we have
no influence on their contents. Therefore, we can also not be held responsible
for this third-party content and we assume no liability. For the contents of
the linked pages the respective providers or operators of the pages are always
responsible.

* Copyright

The content and works on these pages created by the site operators
are subject to Swiss copyright law. The duplication, processing,
distribution and any kind of exploitation outside the limits of
copyrights require the written consent of the respective author
or creator. Downloads and copies of this page are only for private,
non-commercial use permitted. As far as the content on this page
were not created by the operator, the copyrights of third parties
observed. In particular, third-party content is treated as such
marked. If you still notice a copyright infringement
If you become aware of this, we ask that you inform us accordingly. at
As soon as we become aware of legal violations, we will remove such content immediately
remove.

* Privacy

The use of our website is usually without personal information
dates possible. Insofar as personal data is collected on our website
are, as far as possible, always on a voluntary basis
(e.g. own transmission of your data). This data will be without your
express consent not passed on to third parties.

We would like to point out that data transmission on the Internet (e.g. with
the communication via e-mail) may have security gaps. A complete protection
of data against access by third parties is not possible.

The use of contact data published as part of the imprint obligation
by third parties to send unsolicited advertising and
information materials are hereby expressly rejected. The operators
the sides expressly reserve the right to take legal action in the event of
unsolicited sending of advertising information, such as spam e-mails.
