#+TITLE:  Datenschutz / Impressum 
#+AUTHOR: Brian J. Oney
#+TAGS: info
#+ORDER: 9999
#+LANGUAGE: en

* Impressum
Der Inhalt dieser Webseite wurde von Brian J. Oney mit grösster Sorgfalt erstellt. 


* Definitionen
  - Der Autor ist Brian J. Oney.
  - Wissen, Hinweise, Vorschläge dienen Weiterbildung der Leser mit Absicht der Anwendung im Wintersport
  - Die Organisation nennt sich Snowy Experiments.
  - Das männliche Geschlecht im folgenden Text gilt für alle Geschlechter.
  - Ein Nutzer ist eine Person die von dieser Webseite Information holt.
  
* Haftung für Angebot
Auf dieser Webseite werden zu Ausbildungszwecken Informationen angeboten. Diese
Information basieren auf wissenschaftliche Berichte sowie auf Erfahrung des
Autors. Der Einsatz dieser Informationen erfolgt unter der
eigenen Verantwortung und Gefahr. Im Falle von Unfällen und Verletzungen haftet der
Nutzer. Versicherung ist Sache des Teilnehmers.

* Haftung für Inhalte

Die Inhalte unserer Seiten wurden mit grösster Sorgfalt erstellt. Für die
Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch
keine Gewähr übernehmen.  Verpflichtungen zur Entfernung oder Sperrung der
Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon
unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der
Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von
entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.

* Haftung für Links

Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte
wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch
keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der
jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten
Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstösse
überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht
erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist
jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei
Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend
entfernen.

* Urheberrecht

Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten
unterliegen dem Schweizerischen Urheberrecht. Die Vervielfältigung, Bearbeitung,
Verbreitung und jede Art der Verwertung ausserhalb der Grenzen des
Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors
bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten,
nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite
nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter
beachtet. Insbesondere werden Inhalte Dritter als solche
gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung
aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei
Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend
entfernen.

* Datenschutz

Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener
Daten möglich. Soweit auf unseren Seiten personenbezogene Daten erhoben
werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis
(beispielsweise eigene Sendung Ihrer Daten). Diese Daten werden ohne Ihre
ausdrückliche Zustimmung nicht an Dritte weitergegeben.

Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der
Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser
Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.

Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten
durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und
Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber
der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der
unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.

