#+TITLE: Responses to Obvious Questions
#+AUTHOR: Brian J. Oney
#+TAGS: wintercdt
#+LANGUAGE: en

The following answers reflect my experience. I iterate and change my systems
and approaches constantly. I have changed alot of ideas in the past and expect
to change more. Continued learning is one of my core axioms. Please remember
this when you encounter my strong opinions. I experience glee when I have been
proven wrong. Make me happy; convince me otherwise, please.

* This is an extremely dangerous undertaking. Are you crazy?
A wintertime traverse of the CDT could be very dangerous. I am not very
risk-tolerant. With all the tools I have, I can plan out most of the
risk. Furthermore, being in the snow every day gives me insight that I may not
get from an avalanche risk forecast.

The mountains will tell me when to stop.

There indeed are some objectively dangerous sections in Colorado, when the
snowpack is weak, which it usually is. I am not loyal to a snow-covered CDT
footpath. I will optimize for safety and fun, taking the route that makes
sense given the conditions. I will pass through this area when the avalanche
risk is predictable.

Ski traverses are my thing. I am past the phase of needing to prove something
to someone. This idea has gripped me. I will pursue it until it is indeed
crazy. Then I will wait and try again. Everytime I study a map, the slope
angle classes, the distances, study my last trip, I feel good. There are
usually decent exit options, alternate routes, and always the option of
turning back. I got this.

I say this undertaking is ambitious.

"We don’t see things as they are; we see them as we are." - Anonymous

* Do I have to also take scale-based skis?
We will have some flat sections and lots of sections of rolling
terrain. Scale-based skis are the most optimal choice for such travel.  The
minimal downhill disadvantage is more than made up for by the reduced need to
use climbing skins. You glide better when walking, your skis weigh less
without skins, far fewer transitions are necessary, and you make a cool
buzzing sound when you descend! What's not to love about that?

Above all, we need to be on the same page. Scale-based skis are the most
optimal tool for this endeavor as a whole. That is, unless you are a skimo racer who
plans to come with race skis and you can ski them in 3 feet of powder or
facets safely, and comfortably transition in under a minute, every 10 minutes,
with a heavy pack, and are sure that this won't frustrate you.  Otherwise,
yes, you should seriously consider scale-based skis. They make narrower ones, and they
make fatter ones. 

Another idea is to take a second pair of narrow skins (e.g. 3cm wide). 

I see a reasonable exception to this soft requirement. If you wish to join for
a mountainous section where there is little rolling terrain and few flat
sections, where there is a small likelihood that we would not have to reroute
to lower flatter terrain, I guess I will enjoy the different pace. We'd still
need to be within shouting distance, so I expect patience from you when you
are faster, and you can expect patience from me when I am faster.

We both need to be open to ideas for optimizing forward progress. Above all,
we need to be on the same page. I think it is wise to take scale-based skis
for the entirety of the ski traverse. Convince me otherwise.

* How well should I be able to ski?
You should be a pretty good skier. If skiing powder is a challenge, it
will be even harder with a heavy pack pulling you into the back seat. Skiing
breakable crust without proper skill with a heavy pack is injury prone and thus
dangerous. Above all, you should be able to ski safely, even if that is not stylish.

* Why not use cross-country skis?
That may be a good idea. I guess the gear and capabilities of scale-based,
touring skis is just more advanced, that is, lightweight and durable. Also,
the terrain we will be traveling through is too steep for cross-country gear
(and my abilities with cross country skis). If it's an awesome powder day and
we are impeded by avalanche danger, I would probably want to go ride some
powder. I don't have any experience with backcountry cross-country skis, and
consider them to be too specialized for this undertaking. If you wish to join
for a flat section and are comfortable waiting on me for certain areas, then
yes, bring backcountry cross-country skis.

* I'm taking my splitboard, ok?
Comrade, I feel your love for surfing the great white wave. I wish I was still
on a splitboard. It's too inefficient, in my experience. Even with a
split-tech system, the lightest scale-based board (yes, that's a thing), and
world-class condition, you'll probably be too great of a drag and run the risk
of overexertion. What's more important to you?

I was a splitboarder. People on skis were keeping up with me, who should not
have been able to. The efficiency hit is big. I learned to ski because of
that. Long traverses and total immersion in mountains were more important to
me than the ultimate fun on the downhill.  On a traverse, the sum of type
I-fun is greater with skis. Furthermore, the sum of type II-fun is less with
skis. 

A splitboard is less efficient and heavier. The less efficient you are, the
more food you have to eat, the more food and fuel you have to take, the
heavier your pack, the slower you are, the less efficient you are...

Convince me that you've got what it takes to make it fun and safe.

* What if the mother of all storms broadsides us?
We will track weather. Say if we were somehow impeded, and had to hunker down,
we would dig into the snow. In a snowcave, we can regulate the temperature
very well. We will almost always plan on taking 10-20% longer than planned.

Simpler snow caves (torpedo or coffin style) used to be my preferred shelter,
by the way. On a long traverse, it is too much work to be sustainable.

If it's obvious that we will be impeded, we could exit to the nearest town to
wait for conditions to settle. We could also adjust our route to avoid risky
situations, and still hopefully be able to ski the trees.  In total, I plan an
extra 30 to 45 days 'waiting' for safe conditions.
* How do we handle emergency situations?
We don't get into such situations in the first place. We need to have enough
conditioning and skill that we are well within our limits so that we can
comfortably handle expected and unexpected situations.

Should bad luck happen, our skill must suffice to stabilize the situation and
hunker down or exit.

Avalanche: We must not get into an avalanche. We will carry avalanche gear,
but we must not need to use it, unless to help another party.

Gear failure: We fix it to the best of our abilities. We plan on poles breaking, bindings
ripping out, sleeping pads popping. We exit if it's critical and irrepairable (e.g. MSR
Reactor overheats).

Social failure: If we're a pair or a triplet, we stick together, until
reasonable departure is reached i.e. a town or someone with transportation
means. 

Injury: There is a huge body of literature and many courses available. The WFR
course should suffice; take one or refresh. We'll figure things out given the
situation. We prepare ourselves to not sustain an injury, and handle a
situation if the worst happens.

* Why not use a reliable alcohol stove?
I tried my best with the Trail Designs Ti-Tri System. It works and is very
dependable, at altitude and in the cold. It's awesome. And canisters are a
pain in the neck.

But the pinnacle of Trail Designs work is fiddly, slow, and stinks like
hell. In the end, it is also heavier. For a 10-day ski traverse, I need 1.2
liters of ethanol, plus the 400g kit (Toaks 1.3L pot). That will total around
1.6kg. If I take the MSR reactor (490g), with a 450g gas canister (650g), and
the MSR DeepDish bowl (60g) to warm the canister with water, I get better
performance at a lower weight (1.2kg).

But this relationship tips even more in favor of the Reactor, if I have a
partner. Because the Reactor is so fast and with the 1.7L pot size, my
partners only need to carry their gas. The ti-tri would require each partner
to carry their own system to melt snow within a reasonable time. 

The two-person total starting weight comparison tallies Ti-Tri at about 3.2kg
and MSR Reactor system at about 2kg.

The ending weight after 10 days of awesomeness? The alcohol setup is
lighter. One-person end weight of the Tri-tri: 400g, MSR Reactor 750g;
two-person end weight, Ti-Tri: 800g, MSR Reactor 950. If we have three people?
We break even (Ti-Tri 1200g, Reactor 1150g).

But at the end of the awesome 10-day traverse, our packs are empty. All the
time and frustration saved justifies the minimal end weight penalty, even if
I'm alone. The time saved, the starting weight advantage, when everything is
heavier, the ability to comfortably and quickly melt snow in a cabin, tent, or
snow cave make this an easy decision to take the MSR Reactor for winter
outings.

If we're sure we have continued access to water the ti-tri wins out, if we're
melting snow, the MSR Reactor is my suggestion.

* How do we resupply?
We use the normal Post Offices that help out thru-hikers in summertime. Some
are closed in winter, so we need to plan around that. Also, we have a lot of
really nice, selfless people support us with food and fuel caches, or we cache
things ourselves. And we send them thanks and best wishes and cards and
chocolates etc.  We may consider caches for certain remote sections in Montana
and Wyoming.


* In how good of physical condition should I be?
There are two aspects to this. First is the obvious need to be aerobically
well-conditioned i.e. hike all day every day for months. Considerable strength
is also necessary to deal with the weight of the heavier pack. You should be
very injury-resistant. The book 'Training for the Uphill Athlete' is our
training manual.


* What about mental strength?
You should be in good mental shape. Impediments, harsh weather, deep
snow, edgy partners and fatigue are all part of the game. They gnaw at your
mental strength. They can pull you off center. They can disproportionately
subtract from the immense beauty and serenity of the winter landscape. If you
snap, you are in a harsh environment with many objective dangers without your
wits. If you are not skilled at centering yourself, at righting your keeling
ship, this endeavor will not be fun and may be very dangerous. 

We all have our techniques. Ego is a weakness. I recommend Vipassana meditation as
taught by S.N. Goenka.


* Why should I trust you?
You shouldn't. Trust is earned not given. I expect you to ask lots of
questions, poke holes in my plans and approaches, and show me where I am
wrong. I would be incredibly thankful.

There are few people that have the skill and mindset to safely attempt a
winter traverse of the Continental Divide. Considerable vetting is necessary to
make sure that our values and goals align.

* What's your background?
I volunteer for the Swiss Alpine Club. I have attained the certification of
Tourenleiter II. This means that I can guide ski tours on glaciers and
alpine terrain. The necessary skills include avalanche risk assessment,
orienteering, first aid, group management, crevasse (self-)rescue and taking
guests on a short rope.

In contrast to the US system, the Swiss touring culture is quite open and
common. Tour guiding is mostly volunteer and is very prevalent. Switzerland
boasts more than 1,000 mountain guides. The relatively few that decide to
become a full-fledged mountain guides are the professionals that administer
the tour guide courses that I have attended.

I have considered mountain guide certification. After voicing this
consideration, all of my older Swiss mountain guide friends ask me, "Why?!"

It is true; I have apprehension to make my passion a day job. Financing those
adventures would become more challenging, if I were to do it professionally. I
would improve my skills and may have an easier time finding colleagues for my
adventures.

I am still considering. Check out [[../../info/my-story][an abbreviated list]], for more.

Please read about my [[../on-style-and-approach][approach to ski traverses]].

