#+TITLE: Skills and abilities for winter CDT attempt
#+AUTHOR: Brian J. Oney
#+TAGS: wintercdt
#+LANGUAGE: en
#+ORDER: 1

* Requirements
*** Wilderness First Responder
 Many areas of the CDT are very remote, and more so during Winter. We need to
 be able to take care of one another.  I don't have this but will complete a
 NOLS WFR course this fall.  Swiss tour guides only need a first aid course,
 oddly, but that is likely because medical assistance here in Switzerland
 arrives 8-12 minutes(!) after being alerted, if the weather allows.
*** Advanced Downhill Skier
 We will see all snow types. We will be tired and carry heavy packs. We will
 need to be able to safely circumnavigate objective hazards. We need to ski at
 an advanced level.
*** Experienced Winter Camper
 Building a snow cave, choosing a safe campsite, having a dialed winter
 sleeping system down to about -30°C (-23°F) are necessary skills.
* Desirables
*** Avalanche Training
 I guide groups in all avalanche conditions, adjusting to safe terrain,
 dependent on the group's abilities. I would welcome a role-based group
 structure, and can comfortably take the role for assessing avalanche danger. I
 make mistakes, and the more eyes looking at the conditions, the lesser the
 chance of missing signs of danger. If you are an experienced winter
 backcountry ski tourer, you should also have avalanche training. With my
 experience mentoring successful tour guide aspirants, I feel I can help you
 apply your training, but you need the fundamentals first.
*** Mental Strength Training
 Winter is cold, windy and snowy. I love it but it still can get to me. I can
 center myself with meditation. I can forgive harshness, moodiness, etc. and go
 back to being a relaxed and joyful partner. It's a skill. You need to exhibit
 a similar ability when I inevitably forget to be thankful and open. Mental
 resilience is key when we get our butts kicked.
*** Physical conditioning
 We need to be consistently fast. The risk of an overuse injury, overtraining,
 or of a ski injury due to fatigue is high. Carrying a heavy pack through deep
 snow is hard work. Furthermore, we need to be similarly fast. Social tension
 due to differing fitness is a problem. We should complete one of the [[https://UphillAthlete.com][Uphill
 Athlete]] courses (probably the [[https://uphillathlete.com/grand-traverse-ski-training-plan/][12 Week Grand Traverse Training Plan]])
 *together*, at the very least.

