#+TITLE: Skills for ski traversal of CDT 
#+AUTHOR: Brian J. Oney
#+TAGS: wintercdt
#+ORDER: 9
#+LANGUAGE: en

* Requirements
*** Wilderness First Responder
 Many areas of the CDT are very remote, and more so during Winter. We need to
 be able to take care of one another.  I have the WFR-certification,
 completing a NOLS WFR course this fall.  Swiss tour guides only need a first
 aid course, oddly, but that is likely because medical assistance here in
 Switzerland arrives 8-12 minutes(!) after being alerted, if the weather
 allows.
*** Advanced Downhill Skier
 We will see all snow types. We will be tired and carry heavy packs. We will
 need to be able to safely circumnavigate objective hazards. We need to ski at
 an advanced level.
*** Experienced Winter Camper
 Building a snow cave, choosing a safe campsite, having a dialed winter
 sleeping system (down to about -30°C [-23°F]) are necessary skills.
* Desirables
*** Avalanche Training
 I guide groups in all avalanche conditions, adjusting to safe terrain,
 dependent on the group's abilities. I would welcome a role-based group
 structure, and can comfortably take the role for assessing avalanche danger. I
 make mistakes, and the more eyes looking at the conditions, the lesser the
 chance of missing signs of danger. If you are an experienced winter
 backcountry ski tourer, you should also have avalanche training. With my
 experience mentoring successful tour guide aspirants, I feel I can help you
 apply your training, but you need the fundamentals and experience first.
*** Mental Strength Training
 Winter is cold, windy and snowy. I love it but it still can get to
 me. Getting my butt kicked is part of the adventure. I can center myself with
 meditation. I can forgive harshness, moodiness, etc. and go back to being a
 relaxed provider of bad jokes. Centering oneself is a skill. You need to
 also have this ability when I inevitably forget to be thankful and
 open. Mental resilience is key when we get our butts kicked.
*** Physical conditioning
 We need to be consistently fast. The risk of an overuse injury, overtraining,
 or of a ski injury due to fatigue is high. Carrying a heavy pack through deep
 snow is hard work. Furthermore, we need to be similarly fast. Social tension
 due to differing fitness is a problem. We should complete one of the [[https://UphillAthlete.com][Uphill
 Athlete]] courses (probably the Intro to Skimo)
 *together*, at the very least.

