#+TITLE: Winter CDT Book
#+AUTHOR: Brian J. Oney
#+TAGS: wintercdt
#+LANGUAGE: en
#+ORDER: 0

#+OPTIONS: ^:nil


* Why a book?

I write this book for those that helped me along the way, and for my family
and friends. I also add some tidbits for those that enjoy ski traverses, or
may even attempt to do some similarly epic ski traverse. Also, for those
adventurers that like a good story and appreciate an example of someone going ahead
with their crazy idea and succeeding.

For all of you, I am working on a book. It will have prose interlaced with
photos of people and remote places of the US Rocky Mountains. I will do my
absolute best to not disappoint you.

Though very partial, my wife likes my writing style, and, while reading some of the
book, warns me that I won't be going on any such adventures any more, or even
be leaving the house.


* Staying up to date
The below form will subscribe you to a mailing list that I manage with Mailchimp. Write me an e-mail from the link "Get in touch" if you wish that I just email you directly.

#+BEGIN_EXPORT html
<div id="mc_embed_shell">
  <style type="text/css">
        #mc_embed_signup{background:#fff; false;clear:left; font:14px Helvetica,Arial,sans-serif; width: 600px;}
</style>
<div id="mc_embed_signup">
    <form action="https://skitraverse.us21.list-manage.com/subscribe/post?u=44892d7b308264ad62d66094e&amp;id=efc0949fda&amp;f_id=00e4efe6f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_self" novalidate="">
        <div id="mc_embed_signup_scroll"><h5>Subscribe to receive updates</h5>
            <div class="mc-field-group"><label for="mce-EMAIL">Email Address:  </label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""><span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span></div>
        <div id="mce-responses" class="clear foot">
            <div class="response" id="mce-error-response" style="display: none;"></div>
            <div class="response" id="mce-success-response" style="display: none;"></div>
        </div>
    <div aria-hidden="true" style="position: absolute; left: -5000px;">
        /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
        <input type="text" name="b_44892d7b308264ad62d66094e_efc0949fda" tabindex="-1" value="">
    </div>
        <div class="optionalParent">
            <div class="clear foot">
                <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
            </div>
        </div>
    </div>
</form>
</div>
</div>
<br>
#+END_EXPORT
