#+TITLE: Winter CDT Book
#+AUTHOR: Brian J. Oney  
#+DATE: 2023-01-01
#+CATEGORY: winter-cdt
#+PROPERTY: TAGS book, CDT, featured
#+LANGUAGE: en
#+OPTIONS: ^:nil toc:nil
#+SCHEDULED: <2025-12-12 Fri>

* Timeline
- [2024-06-30 Sun] 1st draft scribbled.
- [2024-12-01 Sun] 3rd draft complete.
- [2024-12-08 Sun] Cover art finished.
- [2025-09-03 Wed] Supporter Edition ready for printing.
- [2025-09-12 Tue]-- [2025-09-30 Tue] Book promotion tour, see [[./book-reading-schedule.org][Schedule September 2025]]
- [2025-11-26 Wed] Books ready for print
- [2025-12-12 Fri] Books begin shipping

* Staying up to date
The below form will subscribe you to the mailing list that I manage with Mailchimp. Write me if you wish that I just write you directly. Finally, just return to this page for updates

#+BEGIN_EXPORT html
<div id="mc_embed_shell">
  <style type="text/css">
        #mc_embed_signup{background:#fff; false;clear:left; font:14px Helvetica,Arial,sans-serif; width: 600px;}
</style>
<div id="mc_embed_signup">
    <form action="https://skitraverse.us21.list-manage.com/subscribe/post?u=44892d7b308264ad62d66094e&amp;id=efc0949fda&amp;f_id=00e4efe6f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_self" novalidate="">
        <div id="mc_embed_signup_scroll"><h5>Subscribe to receive updates</h5>
            <div class="mc-field-group"><label for="mce-EMAIL">Email Address:  </label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""><span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span></div>
        <div id="mce-responses" class="clear foot">
            <div class="response" id="mce-error-response" style="display: none;"></div>
            <div class="response" id="mce-success-response" style="display: none;"></div>
        </div>
    <div aria-hidden="true" style="position: absolute; left: -5000px;">
        /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
        <input type="text" name="b_44892d7b308264ad62d66094e_efc0949fda" tabindex="-1" value="">
    </div>
        <div class="optionalParent">
            <div class="clear foot">
                <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
            </div>
        </div>
    </div>
</form>
</div>
</div>
<br>
#+END_EXPORT

* Why a book?

I have written this book for those who helped me along the way, and for my
family and friends. I also write it for lovers of the wilderness, who do not
fear the feeling of insignificance but appreciate it. Some I may even inspire to
attempt some similarly epic ski traverse. Also, for those adventurers who like a
good story and appreciate an example of someone going ahead with their crazy
idea and succeeding, I write this book for you.

The book will have prose interlaced with photos of people and remote places of
the US Rocky Mountains. I will do my absolute best to not disappoint you.

Though very partial, my wife likes my writing style, and, while reading some of the
book, warns me that I won't be going on any such adventures anymore, or even
be leaving the house. I write the book for her as well.
