#+TITLE: Winter CDT Report
#+AUTHOR: Brian J. Oney
#+TAGS: wintercdt
#+LANGUAGE: en
#+ORDER: 0

#+OPTIONS: ^:nil

* Introduction

I completed the first traverse during wintertime of the Continental Divide of
the continental USA. I started hiking from Crazy Cook Monument on November
21st, 2022, a little after noon. I reached the Canadian border on April 15th,
around 1330MST, with my partner Lukas S. But, I was not done. I postponed the
heart of the Colorado Rockies and the northern part of the Wind River Range
until late spring. I finished at the Devil's Thumb Trailhead, near Fraser,
Colorado, on June 3rd, 2023, in the evening after 1900MST.
* Route choice

Although inspired by the Continental Divide Trail (CDT), I strayed often from
the CDT to optimize safety, travel speed, and fun. Downhill skiing the CDT is
not much fun, unless there are otherwise too many fallen trees or other
vegetation.  In a few cases, I also took snowmobile trails for faster travel
and, oftentimes, better scenery.

* My travel


